FROM python:3.6.5-stretch

WORKDIR /usr/src/app

RUN apt-get install git

RUN git clone https://github.com/DocumentBuddy/DocumentBuddy.git

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "./main.py" ]